SANAGER_TESTS_CONFIG_FOLDER=`realpath $(dirname "${BASH_SOURCE[0]}")`
SANAGER_MAIN_DIR=`realpath $(dirname $SANAGER_TESTS_CONFIG_FOLDER)`

# config
DEBIAN_VERSION="13.4.0"
NOWADAYS_DEBIAN_VERSION="trixie"
#DEBIAN_MIRROR_FTP="ftp.cz.debian.org/debian/"
DEBIAN_MIRROR_FTP="ftp.us.debian.org/debian/"

VM_USERS_ROOT_NAME=root
VM_USERS_ROOT_PASSWORD=pswdrootsanager
VM_USERS_SANAGER_NAME=sanager
VM_USERS_SANAGER_PASSWORD=pswdsanager


VM_GROUP_TESTS="/Sanager/Tests"
VM_GROUP_FORKS="/Sanager/Forks"
VM_SSH_TUNNEL_INTERFACE_NAME="Guest SSH tunnel"
VM_NETWORK_DEFINITIONS_FOLDER="$SANAGER_MAIN_DIR/data/virt"
VM_NETWORK_NAME="IsolatedNetwork"
VM_NETWORK_PREFIX="10.155" # should correspond to network used in IsolatedNetwork.xml
VM_CONNECTING_NETWORK_NAME="VmExclusiveNetwork"
VM_ZPOOL_DATASET_PARENT="" # keep blank - it will be overwritten by $TEST_DIR/customConfig.sh

VM_MACHINE_DISK_SIZE_SYSTEM=80G
VM_MACHINE_DISK_SIZE_DATA=8T
VM_MACHINE_DISK_NAME_SYSTEM="system"
VM_MACHINE_DISK_NAME_DATA="data"

TEST_DIR="$SANAGER_MAIN_DIR/.sanagerTests"
VIRTUAL_MACHINES_DIR="$TEST_DIR/virtualMachines"
LOCAL_DEBIAN_MIRROR="$TEST_DIR/DebianMirror"
SANAGER_GUEST_FOLDER_NAME=sanager
SANAGER_GUEST_FOLDER_PATH="/home/$VM_USERS_SANAGER_NAME/$SANAGER_GUEST_FOLDER_NAME"
SANAGER_GUEST_FOLDER_SHARED_PATH="/home/$VM_USERS_SANAGER_NAME/${SANAGER_GUEST_FOLDER_NAME}_shared"
TMP_VM_DEFINITION_PATH="$TEST_DIR/tmpVmDefinition.xml"

# Debian installation-related
NETINSTALL_ORIGINAL_ISO_FILENAME="debian-$DEBIAN_VERSION-amd64-netinst.iso"
NETINSTALL_FINAL_ISO_FILENAME="debian-$DEBIAN_VERSION-amd64-netinst-sanager.iso"
NETINSTALL_ISO_URL="https://cdimage.debian.org/debian-cd/current/amd64/iso-cd/$NETINSTALL_ORIGINAL_ISO_FILENAME"
NETINSTALL_ISO_BUILD_DIR="$TEST_DIR/installIso"
NETINSTALL_ORIGINAL_ISO_FILE="$NETINSTALL_ISO_BUILD_DIR/$NETINSTALL_ORIGINAL_ISO_FILENAME"
NETINSTALL_FINAL_ISO_FILE="$NETINSTALL_ISO_BUILD_DIR/$NETINSTALL_FINAL_ISO_FILENAME"
NETINSTALL_FINAL_ISO_TITLE="Debian Sanager unattended"
NETINSTALL_EXTRA_DATA_DIR="$SANAGER_MAIN_DIR/data/debian/install"

GUEST_SSH_PORT=22

################### VM names ###################################################

# VM essentials
MACHINE_NAME_TEMPORARY="Sanager_Temporary"
MACHINE_NAME_BARE="Sanager_Testing_Bare"
MACHINE_NAME_WITH_OS="Sanager_Testing_WithOS"
MACHINE_NAME_WITH_OS_AND_GUEST_ADDITIONS="Sanager_Testing_WithOS_GuestAdditions"
MACHINE_NAME_STABLE_WITH_SANAGER="Sanager_Testing_WithSanager"

# VM bases - stable/unstable and terminal-only/graphics
MACHINE_NAME_STABLE_TERMINAL_BASE="Sanager_Testing_Stable_TerminalBase"
MACHINE_NAME_STABLE_GRAPHICAL_BASE="Sanager_Testing_Stable_GraphicalBase"
MACHINE_NAME_UNSTABLE_BASE="Sanager_Testing_Unstable_Base"
MACHINE_NAME_UNSTABLE_TERMINAL_BASE="Sanager_Testing_Unstable_TerminalBase"
MACHINE_NAME_UNSTABLE_GRAPHICAL_BASE="Sanager_Testing_Unstable_GraphicalBase"

# VM high levels
MACHINE_NAME_STABLE_HOME_SERVER_TERMINAL="Sanager_Testing_Stable_HomeServerTerminal"
MACHINE_NAME_STABLE_HOME_SERVER_GRAPHICAL="Sanager_Testing_Stable_HomeServerGraphical"
MACHINE_NAME_STABLE_CRYPTO_VISUAL="Sanager_Testing_Stable_CryptoVisual"
MACHINE_NAME_STABLE_GENERAL_USE_VPS="Sanager_Testing_Stable_GeneralUseVps"
MACHINE_NAME_UNSTABLE_PC="Sanager_Testing_Unstable_Pc"
MACHINE_NAME_UNSTABLE_PHYSICAL_PC="Sanager_Testing_Unstable_PhysicalPc"
MACHINE_NAME_UNSTABLE_AI_CORE="Sanager_Testing_Unstable_AiCore"

##################### VM+ZFS disks settings ####################################

# same as OS
ZFS_ZVOL_ARCH_GENERIC="GENERIC"
ZFS_ZVOL_ARCH_GENERIC_VOLBLOCKSIZE=16k
ZFS_ZVOL_ARCH_GENERIC_SYNC=standard
ZFS_ZVOL_ARCH_GENERIC_COMPRESSION=lz4
ZFS_ZVOL_ARCH_GENERIC_PRIMARYCACHE=metadata
ZFS_ZVOL_ARCH_GENERIC_LOGBIAS=latency

ZFS_ZVOL_ARCH_OS="OS"
ZFS_ZVOL_ARCH_OS_VOLBLOCKSIZE=16k
ZFS_ZVOL_ARCH_OS_SYNC=standard
ZFS_ZVOL_ARCH_OS_COMPRESSION=lz4
ZFS_ZVOL_ARCH_OS_PRIMARYCACHE=metadata
ZFS_ZVOL_ARCH_OS_LOGBIAS=latency

ZFS_ZVOL_ARCH_DBPOSTGRES="DBPOSTGRES"
ZFS_ZVOL_ARCH_DBPOSTGRES_VOLBLOCKSIZE=8k
ZFS_ZVOL_ARCH_DBPOSTGRES_SYNC=standard
ZFS_ZVOL_ARCH_DBPOSTGRES_COMPRESSION=lz4
ZFS_ZVOL_ARCH_DBPOSTGRES_PRIMARYCACHE=metadata
ZFS_ZVOL_ARCH_DBPOSTGRES_LOGBIAS=latency

ZFS_ZVOL_ARCH_DBMARIA="DBMARIA"
ZFS_ZVOL_ARCH_DBMARIA_VOLBLOCKSIZE=128k
ZFS_ZVOL_ARCH_DBMARIA_SYNC=lz4
ZFS_ZVOL_ARCH_DBMARIA_COMPRESSION=metadata
ZFS_ZVOL_ARCH_DBMARIA_PRIMARYCACHE=standard
ZFS_ZVOL_ARCH_DBMARIA_LOGBIAS=latency

ZFS_ZVOL_ARCH_BLOCKCHAIN_NODE="BLOCKCHAIN_NODE"
ZFS_ZVOL_ARCH_BLOCKCHAIN_NODE_VOLBLOCKSIZE=8k
ZFS_ZVOL_ARCH_BLOCKCHAIN_NODE_SYNC=standard
ZFS_ZVOL_ARCH_BLOCKCHAIN_NODE_COMPRESSION=lz4
ZFS_ZVOL_ARCH_BLOCKCHAIN_NODE_PRIMARYCACHE=metadata
ZFS_ZVOL_ARCH_BLOCKCHAIN_NODE_LOGBIAS=latency

ZFS_ZVOL_ARCH_AI="AI"
ZFS_ZVOL_ARCH_AI_VOLBLOCKSIZE=8k
ZFS_ZVOL_ARCH_AI_SYNC=standard
ZFS_ZVOL_ARCH_AI_COMPRESSION=lz4
ZFS_ZVOL_ARCH_AI_PRIMARYCACHE=metadata
ZFS_ZVOL_ARCH_AI_LOGBIAS=latency

ZFS_ZVOL_ARCH_GAMING="GAMING"
ZFS_ZVOL_ARCH_GAMING_VOLBLOCKSIZE=8k
ZFS_ZVOL_ARCH_GAMING_SYNC=standard
ZFS_ZVOL_ARCH_GAMING_COMPRESSION=lz4
ZFS_ZVOL_ARCH_GAMING_PRIMARYCACHE=metadata
ZFS_ZVOL_ARCH_GAMING_LOGBIAS=latency
