SANAGER_TESTS_CONFIG_FOLDER=`realpath $(dirname "${BASH_SOURCE[0]}")`
SANAGER_MAIN_DIR=`realpath $(dirname $SANAGER_TESTS_CONFIG_FOLDER)`

# config
DEBIAN_VERSION="13.3.0"
NOWADAYS_DEBIAN_VERSION="trixie"
#DEBIAN_MIRROR_FTP="ftp.cz.debian.org/debian/"
DEBIAN_MIRROR_FTP="ftp.us.debian.org/debian/"

VM_USERS_ROOT_NAME=root
VM_USERS_ROOT_PASSWORD=pswdrootsanager
VM_USERS_SANAGER_NAME=sanager
VM_USERS_SANAGER_PASSWORD=pswdsanager


VM_GROUP_TESTS="/Sanager/Tests"
VM_GROUP_FORKS="/Sanager/Forks"
VM_SSH_TUNNEL_INTERFACE_NAME="Guest SSH tunnel"

TEST_DIR="$SANAGER_MAIN_DIR/.sanagerTests"
VIRTUAL_MACHINES_DIR="$TEST_DIR/virtualMachines"
LOCAL_DEBIAN_MIRROR="$TEST_DIR/DebianMirror"
SANAGER_GUEST_FOLDER_NAME=sanager
SANAGER_GUEST_FOLDER_PATH=/home/$VM_USERS_SANAGER_NAME/$SANAGER_GUEST_FOLDER_NAME

# Debian installation-related
NETINSTALL_ORIGINAL_ISO_FILENAME="debian-$DEBIAN_VERSION-amd64-netinst.iso"
NETINSTALL_FINAL_ISO_FILENAME="debian-$DEBIAN_VERSION-amd64-netinst-sanager.iso"
NETINSTALL_ISO_URL="https://cdimage.debian.org/debian-cd/current/amd64/iso-cd/$NETINSTALL_ORIGINAL_ISO_FILENAME"
NETINSTALL_ISO_BUILD_DIR="$TEST_DIR/installIso"
NETINSTALL_ORIGINAL_ISO_FILE="$NETINSTALL_ISO_BUILD_DIR/$NETINSTALL_ORIGINAL_ISO_FILENAME"
NETINSTALL_FINAL_ISO_FILE="$NETINSTALL_ISO_BUILD_DIR/$NETINSTALL_FINAL_ISO_FILENAME"
NETINSTALL_FINAL_ISO_TITLE="Debian Sanager unattended"
NETINSTALL_EXTRA_DATA_DIR="$SANAGER_MAIN_DIR/data/debian/install"

MACHINE_NAME_TEMPORARY="Sanager_Temporary"
MACHINE_NAME_BARE="Sanager_Testing_Bare"
MACHINE_NAME_WITH_OS="Sanager_Testing_WithOS"
MACHINE_NAME_WITH_OS_AND_GUEST_ADDITIONS="Sanager_Testing_WithOS_GuestAdditions"
MACHINE_NAME_WITH_OS_AND_GUEST_ADDITIONS_UNSTABLE="Sanager_Testing_WithOS_GuestAdditions_Unstable"
MACHINE_NAME_TEST_BASE_PREFIX="Sanager_Testing_Base"
MACHINE_NAME_TEST_PREFIX="Sanager_Testing_Runner_"

SSH_TUNNEL_HOST_PORT=2222
SSH_TUNNEL_HOST_HOSTNAME=127.0.0.1
SSH_TUNNEL_GUEST_PORT=22
